# k6-output-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: k6-output-service
  namespace: k6-monitoring
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "6565"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: k6-runner
  ports:
  - port: 6565
    targetPort: 6565
    protocol: TCP
  type: ClusterIP