apiVersion: apps/v1
kind: Deployment
metadata:
  name: k6-prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k6-prometheus
  template:
    metadata:
      labels:
        app: k6-prometheus
    spec:
      containers:
      - name: k6
        image: grafana/k6:latest
        command: ["sh", "-c"]
        args:
          - |
            # Configurar variables de entorno para k6
            export K6_PROMETHEUS_RW_SERVER_URL=http://localhost:9090/api/v1/write
            export K6_PROMETHEUS_RW_TREND_STATS="p(95),p(50),min,max,avg"
            export K6_PROMETHEUS_RW_INSECURE_SKIP_TLS_VERIFY=true
            
            # Ejecutar k6 con output a Prometheus
            k6 run --out experimental-prometheus-rw /scripts/01_harbor_pull_test_grafana.js &
            
            # Mantener el contenedor activo
            wait
        ports:
        - containerPort: 5656
          name: metrics
        volumeMounts:
        - name: k6-scripts
          mountPath: /scripts
          
      - name: prometheus
        image: prom/prometheus:latest
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: prometheus-config
          mountPath: /etc/prometheus
        command:
        - '/bin/prometheus'
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
        - '--web.console.libraries=/etc/prometheus/console_libraries'
        - '--web.console.templates=/etc/prometheus/consoles'
        - '--web.enable-lifecycle'
        - '--web.enable-remote-write-receiver'  # Importante para recibir métricas de k6
        livenessProbe:
          httpGet:
            path: /-/healthy
            port: 9090
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: k6-scripts
        configMap:
          name: k6-scripts
      - name: prometheus-config
        configMap:
          name: prometheus-config

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    # Remover la configuración de remote_write circular
    # remote_write se maneja desde k6 directamente

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      
      # Si k6 expone métricas en formato Prometheus también
      - job_name: 'k6-metrics'
        static_configs:
          - targets: ['localhost:5656']
        metrics_path: '/metrics'
        scrape_interval: 5s