# k6-artifactory-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: k6-artifactory-test
  namespace: k6-monitoring
spec:
  template:
    metadata:
      labels:
        app: k6-runner
    spec:
      containers:
      - name: k6
        image: grafana/k6:latest
        command: ["k6"]
        args: [
          "run",
          "--out", "prometheus=http://k6-output-service:6565",
          "/scripts/artifactory-test.js"
        ]
        env:
        - name: ARTIFACTORY_URL
          value: "https://artifactory.example.com"
        - name: ARTIFACTORY_USER
          value: "admin"
        - name: ARTIFACTORY_PASS
          value: "password"
        - name: ARTIFACTORY_REPO
          value: "generic-local"
        - name: ARTIFACTORY_FILE
          value: "test/testfile-30mb.bin"
        volumeMounts:
        - name: k6-scripts
          mountPath: /scripts
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: k6-scripts
        configMap:
          name: k6-scripts
      restartPolicy: Never
  backoffLimit: 4