# k6-vault-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: k6-vault-test
  namespace: k6-monitoring
spec:
  template:
    metadata:
      labels:
        app: k6-runner
    spec:
      containers:
      - name: k6
        image: grafana/k6:latest
        command: ["k6"]
        args: [
          "run",
          "--out", "prometheus=http://k6-output-service:6565",
          "/scripts/vault-test.js"
        ]
        env:
        - name: VAULT_URL
          value: "https://vault.example.com"
        - name: VAULT_TOKEN
          value: "s.1234567890abcdef"
        - name: VAULT_SECRET_PATH
          value: "secret/data/test"
        volumeMounts:
        - name: k6-scripts
          mountPath: /scripts
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: k6-scripts
        configMap:
          name: k6-scripts
      restartPolicy: Never
  backoffLimit: 4