# Dockerfile para Ubuntu (última versión LTS)
FROM ubuntu:latest

# Evitar prompts interactivos durante la instalación
ENV DEBIAN_FRONTEND=noninteractive

# Comando por defecto (puede ser sobrescrito al ejecutar el contenedor)
CMD ["/bin/bash"]